"""empty message

Revision ID: 09fe066ed799
Revises: d5d25ca58ca6
Create Date: 2020-08-08 15:07:00.431437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fe066ed799'
down_revision = 'd5d25ca58ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('look',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('look',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
