"""empty message

Revision ID: 28beeaf14055
Revises: 77c2f3932c43
Create Date: 2020-08-12 00:40:42.685071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28beeaf14055'
down_revision = '77c2f3932c43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myprofile', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_myprofile_username_user', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myprofile', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_myprofile_username_user', 'user', ['username'], ['username'], ondelete='CASCADE')
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
