"""empty message

Revision ID: 3dd7b188d724
Revises: b912b51c6ef0
Create Date: 2020-08-11 19:18:48.258852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd7b188d724'
down_revision = 'b912b51c6ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('real_name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('hoby', sa.String(length=200), nullable=True),
    sa.Column('introduce', sa.String(length=200), nullable=True),
    sa.Column('cellphone', sa.Text(), nullable=True),
    sa.Column('modify_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['user.id'], name=op.f('fk_myprofile_email_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['username'], ['user.id'], name=op.f('fk_myprofile_username_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'age', name=op.f('pk_myprofile'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('myprofile')
    # ### end Alembic commands ###
