"""empty message

Revision ID: 8f882f0a3ed3
Revises: cd9834847209
Create Date: 2020-08-11 19:37:55.867491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f882f0a3ed3'
down_revision = 'cd9834847209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myprofile', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_constraint('fk_myprofile_email_user', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myprofile', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_myprofile_email_user', 'user', ['email'], ['email'], ondelete='CASCADE')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
