"""empty message

Revision ID: a074b9b81d6f
Revises: cb94445f005f
Create Date: 2020-08-08 17:46:16.853033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a074b9b81d6f'
down_revision = 'cb94445f005f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_voter1')
    op.drop_table('answer_voter1')
    op.drop_table('comment1')
    op.drop_table('answer1')
    op.drop_table('question1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('modify_date', sa.DATETIME(), nullable=True),
    sa.Column('look', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_question1_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_question1')
    )
    op.create_table('answer1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('modify_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_answer1_question_id_question', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_answer1_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_answer1')
    )
    op.create_table('comment1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('modify_date', sa.DATETIME(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('answer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='fk_comment1_answer_id_answer', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_comment1_question_id_question', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_comment1_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_comment1')
    )
    op.create_table('answer_voter1',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='fk_answer_voter1_answer_id_answer', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_answer_voter1_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answer_id', name='pk_answer_voter1')
    )
    op.create_table('question_voter1',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_question_voter1_question_id_question', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_question_voter1_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id', name='pk_question_voter1')
    )
    # ### end Alembic commands ###
