"""empty message

Revision ID: a693109d2267
Revises: d0e042b88350
Create Date: 2020-08-08 15:23:13.391087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a693109d2267'
down_revision = 'd0e042b88350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('look', sa.Integer(), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('look')

    # ### end Alembic commands ###
