"""empty message

Revision ID: b912b51c6ef0
Revises: 3371edfd2ebd
Create Date: 2020-08-11 16:42:42.734174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b912b51c6ef0'
down_revision = '3371edfd2ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_voter1',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question1.id'], name=op.f('fk_question_voter1_question_id_question1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_question_voter1_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'question_id', name=op.f('pk_question_voter1'))
    )
    op.create_table('answer_voter1',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer1.id'], name=op.f('fk_answer_voter1_answer_id_answer1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_answer_voter1_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answer_id', name=op.f('pk_answer_voter1'))
    )
    with op.batch_alter_table('answer1', schema=None) as batch_op:
        batch_op.drop_constraint('fk_answer1_question_id_question', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_answer1_question_id_question1'), 'question1', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comment1', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment1_answer_id_answer', type_='foreignkey')
        batch_op.drop_constraint('fk_comment1_question_id_question', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment1_answer_id_answer1'), 'answer1', ['answer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment1_question_id_question1'), 'question1', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment1', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment1_question_id_question1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment1_answer_id_answer1'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment1_question_id_question', 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_comment1_answer_id_answer', 'answer', ['answer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('answer1', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_answer1_question_id_question1'), type_='foreignkey')
        batch_op.create_foreign_key('fk_answer1_question_id_question', 'question', ['question_id'], ['id'], ondelete='CASCADE')

    op.drop_table('answer_voter1')
    op.drop_table('question_voter1')
    # ### end Alembic commands ###
