"""empty message

Revision ID: c641d5ac5f8e
Revises: c495937b2294
Create Date: 2020-08-08 15:02:00.993310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c641d5ac5f8e'
down_revision = 'c495937b2294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('look',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('look',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
