"""empty message

Revision ID: cdd265a95739
Revises: 106a7bbeb93e
Create Date: 2020-11-06 13:08:21.784551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd265a95739'
down_revision = '106a7bbeb93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('myprofile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myprofile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('real_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('hoby', sa.VARCHAR(length=200), nullable=True),
    sa.Column('introduce', sa.VARCHAR(length=200), nullable=True),
    sa.Column('cellphone', sa.TEXT(), nullable=True),
    sa.Column('modify_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user.username'], name='fk_myprofile_username_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'age', name='pk_myprofile')
    )
    # ### end Alembic commands ###
