"""empty message

Revision ID: d0e042b88350
Revises: 34636e0d0b44
Create Date: 2020-08-08 15:20:23.393364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e042b88350'
down_revision = '34636e0d0b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('look')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('look', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
