"""empty message

Revision ID: d5d25ca58ca6
Revises: c641d5ac5f8e
Create Date: 2020-08-08 15:04:51.512064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d25ca58ca6'
down_revision = 'c641d5ac5f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('look',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('look',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
