"""empty message

Revision ID: dc81d312f69d
Revises: 32d7dd54e48a
Create Date: 2020-08-11 19:23:24.953678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc81d312f69d'
down_revision = '32d7dd54e48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myprofile', schema=None) as batch_op:
        batch_op.drop_constraint('fk_myprofile_username_user', type_='foreignkey')
        batch_op.drop_constraint('fk_myprofile_email_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_myprofile_email_user'), 'user', ['email'], ['email'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_myprofile_username_user'), 'user', ['username'], ['username'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myprofile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_myprofile_username_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_myprofile_email_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_myprofile_email_user', 'user', ['email'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_myprofile_username_user', 'user', ['username'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
